### ISSUE TITLE
Bug in example.py

### ISSUE THREAD

**Issue by TK12331** [THUYimingLi/BackdoorBox#50]
Traceback (most recent call last):
  File "/home/objdet/Desktop/backdoor/BackdoorBox/example.py", line 66, in <module>
    badnets = core.BadNets(
TypeError: __init__() got an unexpected keyword argument 'poisoned_transform_index'

When I ran the code example.py, the above error was thrown out. And I have checked the code in core/attacks/BadNets, it does not have the argument poisoned_transform_index in function __init__().

Could you fix the bug?

Thanks.

**Comment by TK12331** [comment]
I found that just commenting it out and using the default parameter works fine.

**Comment by THUYimingLi** [comment]
> 

Hi, TK12331, thx for your attention to our toolbox! Firstly, this argument is included in base.py instead of BadNets.py where BadNets.py inherites somes function of base.py. Besides, I am deeply sorry that we forget to remove or update example.py since it is written based on our old version that could be changed.

Please use the example codes in test subfolder instead :)

**Comment by THUYimingLi** [comment]
> Traceback (most recent call last): File "/home/objdet/Desktop/backdoor/BackdoorBox/example.py", line 66, in badnets = core.BadNets( TypeError: **init**() got an unexpected keyword argument 'poisoned_transform_index'
> 
> When I ran the code example.py, the above error was thrown out. And I have checked the code in core/attacks/BadNets, it does not have the argument poisoned_transform_index in function **init**().
> 
> Could you fix the bug?
> 
> Thanks.

Hi, TK12331, thx for your attention to our toolbox! Firstly, this argument is included in base.py instead of BadNets.py where BadNets.py inherites somes function of base.py. Besides, I am deeply sorry that we forget to remove or update example.py since it is written based on our old version that could be changed.

Please use the example codes in test subfolder instead :)

**Comment by THUYimingLi** [comment]
I will turn off this issue If you don't have additional questions. Thanks again for using our toolbox!
