### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by zemingyao** [THUYimingLi/BackdoorBox#81]
Hi! We are really interested in your paper. It's mentioned that even without User Manual, it's very easy to test any attack methods under the subfolder "tests". However,when we tried to run the code, the code met several issues like parameter setting & cannot load the local module properly. Could you please upload a User Manual? It will do a great favor to those who are looking forward to using this amazing tool and cite this in future paper. Thank you!

**Comment by THUYimingLi** [comment]
> Hi! We are really interested in your paper. It's mentioned that even without User Manual, it's very easy to test any attack methods under the subfolder "tests". However,when we tried to run the code, the code met several issues like parameter setting & cannot load the local module properly. Could you please upload a User Manual? It will do a great favor to those who are looking forward to using this amazing tool and cite this in future paper. Thank you!

Hi, thanks for reaching out! However, due to the limitation of time and our current work plan, we may not able to write a user manual recently. We have used codes under the subfolder "tests" to evaluate and record all our methods. We believe that you can easily fix your bugs by assigning a proper value to all locations where the data or model are loaded :)
